### ISSUE TITLE
Architecture review 

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#176] opened 2022-07-26 16:15 UTC
Review how the current system works and we can improve to make sure it can scale to thousands of probes with hundreds of measurements requesting hundreds of tests per second.

Related issues:
- A random user took the system down with only a few hundreds of tests according to appsignal https://github.com/jsdelivr/globalping/issues/132
- He actually got 60+ probes of ours to get stuck forever by sending something, we're not sure why. That's why we've added frequent forced reboots.
- How many tests can the probes handle? Do we have bottlenecks there? https://github.com/jsdelivr/globalping-probe/issues/10
- During my own tests sometimes when I click "run" too hard I get timeouts, "finished" tests with no output and other random issues that are too difficult to replicate
- Our logs are filled with probes disconnecting and re-connecting for no apparent reason https://github.com/jsdelivr/globalping/issues/124
- Multi-instance API is not working correctly https://github.com/jsdelivr/globalping/issues/120
- Need to find a way for graceful deployments and restarts https://github.com/jsdelivr/globalping/issues/95 (task may not be relevant if we switch away from Heroku, but any new system would still need HA)
- Potentially figure out native APM integration to have better view of what is going on inside the system https://github.com/jsdelivr/globalping/issues/131

**Comment by patrykcieszkowski** [comment] 2022-07-29 12:43
We should probably replace the timeout logic, I can't imagine it would scale well.

https://github.com/jsdelivr/globalping/blob/master/src/measurement/runner.ts#L91

**Comment by MartinKolarik** [comment] 2022-07-29 12:51
Scale well in what sense? That actually seems quite ok (somewhat related, lru-cache uses a timer per key and it's ok https://github.com/isaacs/node-lru-cache/issues/208#issuecomment-1064354817).

**Comment by patrykcieszkowski** [comment] 2022-07-29 13:00
It spawns an internal timer per every measurement, and holds them locally. If the API goes down, the timer is gone, and the status is never marked as `finished`, unless the result comes - which is not guaranteed.

A way better solution would be to have a global interval running per each API instance, and just query unresolved measurements older than X.

**Comment by MartinKolarik** [comment] 2022-07-29 13:32
Or a task queue for the measurements, which may very well be fallout from this task. We'll see.

**Comment by jimaek** [comment] 2022-08-03 10:07
Btw in the review it probably also makes sense to account for the future scheduled tests feature. Where we would need a time series database to store continuous results of a single measurement. E.g. monitor the performance of DNS and CDN providers 

Too many options in terms of DB as well

**Comment by MartinKolarik** [comment] 2022-10-02 21:30
Current status:

1. Probe performance:
1.1 Very good and can be further improved for HTTP tests (https://github.com/jsdelivr/globalping-probe/issues/100)
1.2 Not so good but acceptable for now for other tests. Improving it not so easy (pool of processes, which requires support to run the tools in interactive mode or implementing them directly in node, which wouldn't work for all our config options).

2. API performance:
2.1 The current single process breaks with 2 - 4 tests that run on 500 probes - a big problem.
2.2 Support for multiple independed API processes needed (#120).
2.3 Most of the "work" the API does is handling status updates from the probes and writing them to redis. A single test typically sends several updates (start, partial results a few times, final result), and if a test is run on the max 500 probes, it can result in 2k-3k messages in total. This needs to be made as efficient as possible. We can, if it helps, throttle the partial updates a but using the following logic: send the first part of output right away, then an update at most once a second, and then the final result as soon as the measurement is fully done.

**Comment by alexey-yarmosh** [comment] 2022-10-04 07:26
My current plan is to focus on the API first:
1. Reproduce the API issue (https://github.com/jsdelivr/globalping/issues/132) on the env.
2. Try to reproduce the same issue locally.
3. Address https://github.com/jsdelivr/globalping/issues/131 so we will be able to analyze the behavior and find the possible solution.
4. Try to find the bottleneck and a possible fix.

**Comment by MartinKolarik** [comment] 2022-10-04 21:59
One more related problem that I don't think we documented anywhere yet. We store test results for 7 days but have nowhere near the HW to actually do that with the real usage because the redis instance only has 100 MB of memory. Of course, we'll move to a higher plan, but even then, it's questionable - how many results can we roughly fit into a 16/32/64 GB memory server, and is that enough for a full week?

If not, we should think about possibly splitting the data, and as I see it, there are three categories of what we store:
 1. information about probes (not too much data, moderate IO),
 2. results of the currently running tests (more data, heavy IO),
 3. results of the past (up to 7 days) tests (a lot of data, little IO),

If needed, these could be separate servers. For the test results, they could utilize sharding, or the "past data" category could even use a different database (e.g. move from 2 to 3 after an hour).

**Comment by alexey-yarmosh** [comment] 2022-10-05 12:15
> 1. information about probes (not too much data, moderate IO)

As far as I see, we are storing active probes info in a node process memory.

Anyway I got the idea, I'll create an issue for that.

**Comment by jimaek** [comment] 2022-10-05 12:19
Note that we can and probably should lower the storage of tests based on user level. E.g. anons store for 12 hours, free registered 24 hours, sponsors 7 days

**Comment by jimaek** [comment] 2022-10-22 11:40
Plan so far for new prod:
- 2 dedi servers with 8 threads + 64GB RAM
- Managed by docker swarm https://github.com/jsdelivr/globalping/blob/master/compose-stack.yml
- Separate dedi or VM for Redis. Mem size to be decided but probably 64GB
- No new components introduced


To do to support the new prod:
- Avoid using CDN and install SSL on a node.js level with auto-updates from letsencrypt
- Fix multi-instance API and probe syncing
- Scale to all available cores. 8 per server, total 16.
- Make sure the API can handle the docker overlay network. Meaning if a user connects to server1 in reality they could be routed internally to server2. So the IP the probe and user connect to doesnt mean anything, they could be connected to any underlying API instance.
- Gracefully handle 0-downtime deployments. Currently Docker will shut down 1 instance and wait a few seconds, deploy new container, wait and then continue with shutting down the second instance. The API should listen for TERM signals, stop accepting tests and probes,  and force connected probes and users to re-connect to the other instance.
- Depending on how long the above process takes we will need to update the timeout values in https://github.com/jsdelivr/globalping/blob/master/compose-stack.yml

**Closed** 2022-11-09 17:55 UTC
